### ISSUE TITLE
Unsure how to configure syntax highlighting

### ISSUE THREAD

**Issue by photex** [dgriffen/rls-vs2017#17]
Howdy!

I'm trying to figure out where the colors for the syntax highlighting of Rust files are configured. It doesn't match my C++ settings, and as I've just now discovered there is a bucket of ugly defaults in Visual Studio and I have no clue which applies to what.

Cheers!

**Comment by dgriffen** [comment]
The syntax highlighting is controlled by textmate files shipped with visual studio. You can find the rust textmate file in `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TextMate\Starterkit\Extensions\rust\syntaxes`. Unfortunately configuring textmate highlighting is a bit complicated and not documented very well.

**Comment by photex** [comment]
Awesome thanks for explaining this. I'm happy enough to leave things as they are for now. I just sucked it up and dug through the font and color settings. I'm very acclimated to the Jetbrains universe where each language is configured separately but inherit a common language theme.
