### ISSUE TITLE
Change location of target/rls directory

### ISSUE THREAD

**Issue by skuzins** [dgriffen/rls-vs2017#22]
Is there a way to accomplish this? Quoting https://github.com/rust-lang/rls/issues/870#issuecomment-389286606

> Language clients need to use the LSP workspace/didChangeConfiguration to pass the rust.target_dir key

**Comment by dgriffen** [comment]
Yes, you can follow the documentation [here](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension?view=vs-2017#user-editing-of-settings-for-a-workspace) to add a JSON file with custom workspace settings.

**Comment by skuzins** [comment]
Thanks! I created VSWorkspaceSettings.json in .vs and tried various properties but they don't seem to get picked up. Any ideas?

```
{
  "rust.target_dir" : "test_target/rls"
}
```
as well as plain target_dir and RustLanguageExtension.target_dir
